### ISSUE TITLE
./msfconsole error

### ISSUE THREAD

**Issue by hktalent** [pwnwiki/q#21]
xx

**Comment by hktalent** [comment]
$ ./msfconsole -m
/Users/xiatian/safe/metasploit-framework/lib/metasploit/framework/parsed_options/base.rb:42:in `initialize': missing argument: -m (OptionParser::MissingArgument)
	from /Users/xiatian/safe/metasploit-framework/lib/metasploit/framework/command/base.rb:69:in `new'
	from /Users/xiatian/safe/metasploit-framework/lib/metasploit/framework/command/base.rb:69:in `parsed_options'
	from /Users/xiatian/safe/metasploit-framework/lib/metasploit/framework/command/base.rb:47:in `require_environment!'
	from /Users/xiatian/safe/metasploit-framework/lib/metasploit/framework/command/base.rb:81:in `start'
	from ./msfconsole:48:in `<main>'

**Comment by darkoperator** [comment]
This is do to a recent change in the class name for the modules in Metasploit, all the modules need to change the name of the class they inherit from in the code to fix the issue.

**Comment by darkoperator** [comment]
The fix should be a simple one 
You can make that update to all your custom modules with this one-liner on linux:

`find ~/.msf4/modules -name '*.rb' | xargs sed -i 's/class Metasploit[34]/class MetasploitModule/'`

If you're on OS X, your sed(1) is dumb and requires an argumen to -i:

`find ~/.msf4/modules -name '*.rb' | xargs sed -i '' 's/class Metasploit[34]/class MetasploitModule/'`

**Comment by mononoke1203** [comment]
hey. I got the same problem than hktalent. But if I enter your command
find ~/.msf4/modules -name '*.rb' | xargs sed -i 's/class Metasploit[34]/class MetasploitModule/'
nothing happens. I'm using Linux Kali (if this changes something?!)
please help. thanks!

**Comment by darkoperator** [comment]
It changes the class name of each module to the new format. Surprised this has not been fixed in so long.

**Comment by ghost** [comment]
problem solved. thanks for your help anyway!!!! 
I'm quite new to linux and hacking. thats why I got some issues but finally I solved it :+1:
