### ISSUE TITLE
small bug passwd-shadow-ssh-jacker-shell.rb

### ISSUE THREAD

**Issue by x00en5** [pwnwiki/q#3]
passwd-shadow-ssh-jacker-shell.rb
seems to be missing an extra keyword 'end' at line 76

# msfconsole 
[-] WARNING! The following modules could not be loaded!
[-]     /opt/metasploit/msf3/modules/post/linux/q/passwd-shadow-ssh-jacker-shell.rb: SyntaxError /opt/metasploit/msf3/modules/post/linux/q/passwd-shadow-ssh-jacker-shell.rb:76: syntax error, unexpected $end, expecting keyword_end
**_snip**_
       =[ metasploit v4.5.0-dev [core:4.5 api:1.0]

adding the 'end' resolves the issue

**Comment by mubix** [comment]
On it. Thanks for the report
